apiVersion: v1
kind: Service
metadata:
  name: {{ include "expense-tracker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "expense-tracker.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
