# Fill in from: terraform -chdir=../../environments/dev output
image:
  repository: "REPLACE_WITH_ECR_REPOSITORY_URL"
  tag: "dev"

replicaCount: 1

serviceAccount:
  roleArn: "REPLACE_WITH_DEV_IRSA_APP_ROLE_ARN"

config:
  dbHost: "REPLACE_WITH_DEV_RDS_ENDPOINT"
  dbPort: "5432"
  dbName: "expenses"
  dbSecretArn: "REPLACE_WITH_DEV_RDS_MASTER_USER_SECRET_ARN"
  s3Bucket: "REPLACE_WITH_DEV_APP_S3_BUCKET_NAME"
  awsRegion: "us-east-1"
  appEnv: "dev"
