image:
  repository: "395675597879.dkr.ecr.us-east-1.amazonaws.com/k8s-platform-app-dev"
  tag: "app-dev-20260711-212500"
replicaCount: 1
serviceAccount:
  roleArn: "arn:aws:iam::395675597879:role/k8s-platform-dev-app"
config:
  dbHost: "k8s-platform-dev-db.cots7ubp4aji.us-east-1.rds.amazonaws.com"
  dbPort: "5432"
  dbName: "expenses"
  dbSecretArn: "arn:aws:secretsmanager:us-east-1:395675597879:secret:rds!db-ab390975-19b5-486a-920f-34ea5cba224b-le3l1z"
  s3Bucket: "k8s-platform-app-dev-395675597879"
  awsRegion: "us-east-1"
  appEnv: "dev"
frontend:
  image:
    repository: "395675597879.dkr.ecr.us-east-1.amazonaws.com/k8s-platform-frontend-dev"
    tag: "web-dev-20260711-212500"
  replicaCount: 1
